CREATE DATABASE ACIDENTES_AEREOS;

USE ACIDENTES_AEREOS;

--Trigrama = PAS
CREATE TABLE PAISES(
	PAS_ID INT IDENTITY,
	PAS_NOME VARCHAR(100) NOT NULL,
	CONSTRAINT PK_PAS PRIMARY KEY(PAS_ID)
);


--Trigrama = QTM
CREATE TABLE QUANTIDADES_MOTORES(
	QTM_ID INT IDENTITY,
	QTM_Tipo VARCHAR(100) NOT NULL,
	CONSTRAINT PK_QTM PRIMARY KEY(QTM_ID)
);

--Trigrama = TPI
CREATE TABLE TIPOS_ICAO(
	TPI_ID INT IDENTITY,
	TPI_ICAO CHAR(4) NOT NULL,
	CONSTRAINT PK_TPI PRIMARY KEY(TPI_ID)
);


--Trigrama = PMD
CREATE TABLE PESOS_MAXIMOS_DECOLAGEM(
	PMD_ID INT IDENTITY,
	PMD_PESO INT NOT NULL,
	CONSTRAINT PK_PMD PRIMARY KEY(PMD_ID)
);


--Trigrama = FBA
CREATE TABLE FABRICANTES_AERONAVES(
	FBA_ID INT IDENTITY,
	FBA_NOME VARCHAR(300) NOT NULL,
	CONSTRAINT PK_FBA PRIMARY KEY(FBA_ID)
);


--Trigrama = TPA
CREATE TABLE TIPOS_AERONAVE(
	TPA_ID INT IDENTITY,
	TPA_TIPO VARCHAR(150) NOT NULL,
	CONSTRAINT PK_TPA PRIMARY KEY(TPA_ID)
);


--Trigrama = TPM
CREATE TABLE TIPOS_MOTORES(
	TPM_ID INT IDENTITY,
	TPM_TIPO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_TPM PRIMARY KEY (TPM_ID) 
);


--Trigrama = TPS
CREATE TABLE TIPOS_SEGMENTOS(
	TPS_ID INT IDENTITY,
	TPS_OPERACAO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_TPS PRIMARY KEY(TPS_ID)
);

--Trigrama = CAO
CREATE TABLE CATEGORIAS_OCORRENCIAS(
	CAO_ID INT IDENTITY,
	CAO_CATEGORIA VARCHAR(250) NOT NULL,
	CAO_SIGLA VARCHAR(20) NOT NULL,
	CONSTRAINT PK_CAO PRIMARY KEY(CAO_ID)
);

--Trigrama = ARD
CREATE TABLE AERODROMOS(
	ARD_ID INT IDENTITY,
	ARD_SIGLA VARCHAR(20),
	CONSTRAINT PK_ARD PRIMARY KEY (ARD_ID)
);


--Trigrama = TPF
CREATE TABLE TIPOS_FALHAS(
	TPF_ID INT IDENTITY,
	TPF_TIPO VARCHAR(200) NOT NULL,
	CONSTRAINT PK_TPF PRIMARY KEY(TPF_ID)
);

--Trigrama = AAS
CREATE TABLE ASPECTOS_ACIDENTES(
	AAS_ID INT IDENTITY,
	AAS_ASPECTO VARCHAR(120),
	CONSTRAINT PK_AAS PRIMARY KEY (AAS_ID)
);

--Trigrama = CDA
CREATE TABLE CONDICIONANTES_ACIDENTES(
	CDA_ID INT IDENTITY,
	CDA_CONDICIONANTE VARCHAR(200) NOT NULL,
	CONSTRAINT PK_CDA PRIMARY KEY (CDA_ID)
);

--Trigrama = FAC
CREATE TABLE FATORES_ACIDENTES(
	FAC_ID INT IDENTITY,
	FAC_NOME VARCHAR(200) NOT NULL,
	CONSTRAINT PK_FAC PRIMARY KEY(FAC_ID)
);

--Trigrama = CLA
CREATE TABLE CLASSIFICACOES_ACIDENTES(
	CLA_ID INT IDENTITY,
	CLA_CLASSIFICACAO VARCHAR(100) NOT NULL,
	CONSTRAINT PK_CLA PRIMARY KEY (CLA_ID)
);

--Trigrama = NVA
CREATE TABLE NIVEIS_DANOS_ACIDENTES(
	NVA_ID INT IDENTITY,
	NVA_NIVEL VARCHAR (100) NOT NULL,
	CONSTRAINT PK_NVA PRIMARY KEY (NVA_ID)
);

--Trigrama = EST
CREATE TABLE ESTADOS(
	EST_ID INT IDENTITY,
	EST_UF VARCHAR(5) NOT NULL,
	EST_PAS_ID INT NOT NULL
	CONSTRAINT PK_EST PRIMARY KEY(EST_ID),
	CONSTRAINT FK_EST_PAS FOREIGN KEY(EST_PAS_ID) REFERENCES PAISES (PAS_ID)
);

--Trigrama = MUC
CREATE TABLE MUNICIPIOS(
	MUC_ID INT IDENTITY,
	MUC_NOME VARCHAR(200) NOT NULL,
	MUC_EST_ID INT NOT NULL,
	CONSTRAINT PK_MUC PRIMARY KEY(MUC_ID),
	CONSTRAINT FK_MUC_EST FOREIGN KEY (MUC_EST_ID) REFERENCES ESTADOS(EST_ID)
);

--Trigrama = MDA
CREATE TABLE MODELOS_AERONAVES(
	MDA_ID INT IDENTITY,
	MDA_MODELO VARCHAR (100) NOT NULL,
	MDA_ASSENTOS INT NOT NULL,
	MDA_FBA_ID INT NOT NULL,
	MDA_TPI_ID INT NOT NULL, 
	MDA_PMD_ID INT NOT NULL,
	MDA_TPA_ID INT NOT NULL,
	CONSTRAINT PK_MDA PRIMARY KEY(MDA_ID),
	CONSTRAINT FK_MDA_FBA FOREIGN KEY(MDA_FBA_ID) REFERENCES FABRICANTES_AERONAVES(FBA_ID),
	CONSTRAINT FK_MDA_TPI FOREIGN KEY(MDA_TPI_ID) REFERENCES TIPOS_ICAO(TPI_ID),
	CONSTRAINT FK_MDA_PMD FOREIGN KEY(MDA_PMD_ID) REFERENCES PESOS_MAXIMOS_DECOLAGEM(PMD_ID),
	CONSTRAINT FK_MDA_TPA FOREIGN KEY(MDA_TPA_ID) REFERENCES TIPOS_AERONAVE(TPA_ID)
);


--Trigrama = ARV
CREATE TABLE AERONAVES(
	ARV_ID INT IDENTITY,
	ARV_MATRICULA VARCHAR(20) NOT NULL,
	ARV_ANO_FABRICACAO CHAR(4) NOT NULL,
	ARV_MDA_ID INT NOT NULL,
	ARV_QTM_ID INT NOT NULL,
	ARV_TPM_ID INT NOT NULL,
	ARV_PAS_ID INT NOT NULL,
	CONSTRAINT PK_ARV PRIMARY KEY(ARV_ID),
	CONSTRAINT FK_ARV_MDA FOREIGN KEY(ARV_MDA_ID) REFERENCES MODELOS_AERONAVES(MDA_ID),
	CONSTRAINT FK_ARV_QTM FOREIGN KEY(ARV_QTM_ID) REFERENCES QUANTIDADES_MOTORES(QTM_ID),
	CONSTRAINT FK_ARV_TPM FOREIGN KEY(ARV_TPM_ID) REFERENCES TIPOS_MOTORES(TPM_ID),
	CONSTRAINT FK_ARV_PAS FOREIGN KEY(ARV_PAS_ID) REFERENCES PAISES(PAS_ID)
);

--Trigrama = OAC
CREATE TABLE OCORRENCIAS_AERONAVES(
	OAC_ID INT IDENTITY,
	OAC_CODIGO VARCHAR(30) NOT NULL,
	OAC_LATITUDE VARCHAR(100) NOT NULL,
	OAC_LONGITUTDE VARCHAR(100) NOT NULL,
	OAC_DIA DATE NOT NULL,
	OAC_HORARIO TIME NOT NULL,
	OAC_TOTAL_AERONAVES INT NOT NULL,
	OAC_FATALIDADES INT NOT NULL,
	OAC_SAIDA_PISTA CHAR(3) NOT NULL,
	OAC_ARV_ID INT NOT NULL,
	OAC_MUC_ID INT NOT NULL,
	OAC_ARD_ID INT NOT NULL,
	OAC_TPS_ID INT NOT NULL,
	OAC_CAO_ID INT NOT NULL,
	OAC_CLA_ID INT NOT NULL,
	OAC_NVA_ID INT NOT NULL,
	CONSTRAINT PK_OAC PRIMARY KEY (OAC_ID),
	CONSTRAINT FK_OAC_ARV FOREIGN KEY(OAC_ARV_ID) REFERENCES AERONAVES(ARV_ID),
	CONSTRAINT FK_OAC_MUC FOREIGN KEY(OAC_MUC_ID) REFERENCES MUNICIPIOS(MUC_ID),
	CONSTRAINT FK_OAC_ARD FOREIGN KEY(OAC_ARD_ID) REFERENCES AERODROMOS(ARD_ID),
	CONSTRAINT FK_OAC_TPS FOREIGN KEY(OAC_TPS_ID) REFERENCES TIPOS_SEGMENTOS(TPS_ID),
	CONSTRAINT FK_OAC_CAO FOREIGN KEY(OAC_CAO_ID) REFERENCES CAREGORIAS_OCORRENCIAS(CAO_ID),
	CONSTRAINT FK_OAC_CLA FOREIGN KEY(OAC_CLA_ID) REFERENCES CLASSIFICACOES_ACIDENTES(CLA_ID),
	CONSTRAINT FK_OAC_NVA FOREIGN KEY(OAC_NVA_ID) REFERENCES NIVEIS_DANOS_ACIDENTES(NVA_ID)
);
