USE ACIDENTES_AEREOS;

DELETE MODELOS_AERONAVES;
DELETE PAISES;
DELETE TIPOS_ICAO;
DELETE PESOS_MAXIMOS_DECOLAGEM;
DELETE TIPOS_AERONAVE;
DELETE TIPOS_MOTORES;
DELETE FABRICANTES_AERONAVES;
DELETE QUANTIDADES_MOTORES;
DELETE NIVEIS_DANOS_ACIDENTES


select * from paises;