USE ACIDENTES_AEREOS;

DROP PROCEDURE Proc_InserirPaises;
DROP PROCEDURE Proc_InserirTipoIcao;
DROP PROCEDURE Proc_InserirPMD;
DROP PROCEDURE Proc_InserirTipoAeronave;
DROP PROCEDURE Proc_InserirFabricanteAeronave;
DROP PROCEDURE Proc_InserirModelosAeronaves;
DROP PROCEDURE Proc_InserirTipoMotores;
DROP PROCEDURE Proc_InseririQuantidadeMotores;
DROP PROCEDURE Proc_InserirNiveisDados;
DROP PROCEDURE DistribuirDadosAeronave;

--RESET Auto incremente
DBCC CHECKIDENT ('PAISES', RESEED, 0);
DBCC CHECKIDENT ('TIPOS_ICAO', RESEED, 0);
DBCC CHECKIDENT ('PESOS_MAXIMOS_DECOLAGEM', RESEED, 0);
DBCC CHECKIDENT ('TIPOS_AERONAVE', RESEED, 0);
DBCC CHECKIDENT ('FABRICANTES_AERONAVES', RESEED, 0);
DBCC CHECKIDENT ('TIPOS_MOTORES', RESEED, 0);
DBCC CHECKIDENT ('MODELOS_AERONAVES', RESEED, 0);
DBCC CHECKIDENT ('QUANTIDADES_MOTORES', RESEED, 0);
DBCC CHECKIDENT ('NIVEIS_DANOS_ACIDENTES', RESEED, 0);


--Drop planilha
DROP TABLE planilha_aeronave;