USE ACIDENTES_AEREOS;
GO

DROP PROCEDURE Proc_InserirPaises;
DROP PROCEDURE Proc_InserirTipoIcao;
DROP PROCEDURE Proc_InserirPMD;
DROP PROCEDURE Proc_InserirTipoAeronave;
DROP PROCEDURE Proc_InserirFabricanteAeronave;
DROP PROCEDURE Proc_InserirModelosAeronaves;
DROP PROCEDURE Proc_InserirTipoMotores;
DROP PROCEDURE Proc_InseririQuantidadeMotores;
DROP PROCEDURE Proc_InserirNiveisDados;
DROP PROCEDURE Proc_InserirTiposSegmentos;
DROP PROCEDURE Proc_InserirAeronaves;
DROP PROCEDURE Proc_InserirEstados;
DROP PROCEDURE Proc_InserirMunicipio;
DROP PROCEDURE Proc_ClassificacaoAcidentes;
DROP PROCEDURE Proc_InserirAerodromos;
DROP PROCEDURE Proc_InserirCategoriaOcorrencia;
DROP PROCEDURE Proc_InserirOcorrencias;
DROP PROCEDURE Proc_InserirTIposFalhas;
DROP PROCEDURE Proc_InserirCondicionantesAcidentes;
DROP PROCEDURE Proc_InserirAspectosAcidentes;
DROP PROCEDURE Proc_InserirFatoresAcidentes;
DROP PROCEDURE Proc_InserirInvestigacoes;
DROP PROCEDURE DistribuirDados;

GO

--RESET Auto incremente
DBCC CHECKIDENT ('PAISES', RESEED, 0);
DBCC CHECKIDENT ('TIPOS_ICAO', RESEED, 0);
DBCC CHECKIDENT ('PESOS_MAXIMOS_DECOLAGEM', RESEED, 0);
DBCC CHECKIDENT ('TIPOS_AERONAVE', RESEED, 0);
DBCC CHECKIDENT ('FABRICANTES_AERONAVES', RESEED, 0);
DBCC CHECKIDENT ('TIPOS_MOTORES', RESEED, 0);
DBCC CHECKIDENT ('MODELOS_AERONAVES', RESEED, 0);
DBCC CHECKIDENT ('QUANTIDADES_MOTORES', RESEED, 0);
DBCC CHECKIDENT ('NIVEIS_DANOS_ACIDENTES', RESEED, 0);
DBCC CHECKIDENT ('TIPOS_SEGMENTOS', RESEED, 0);
DBCC CHECKIDENT ('AERONAVES', RESEED, 0);
DBCC CHECKIDENT ('ESTADOS',RESEED,0);
DBCC CHECKIDENT ('MUNICIPIOS',RESEED,0);
DBCC CHECKIDENT ('CLASSIFICACOES_ACIDENTES', RESEED,0);
DBCC CHECKIDENT ('AERODROMOS', RESEED,0);
DBCC CHECKIDENT ('CATEGORIAS_OCORRENCIAS', RESEED,0);
DBCC CHECKIDENT ('OCORRENCIAS_AERONAVES', RESEED,0);
DBCC CHECKIDENT ('TIPOS_FALHAS', RESEED,0);
DBCC CHECKIDENT ('CONDICIONANTES_ACIDENTES', RESEED,0);
DBCC CHECKIDENT ('ASPECTOS_ACIDENTES', RESEED,0);
DBCC CHECKIDENT ('FATORES_ACIDENTES', RESEED,0);
DBCC CHECKIDENT ('INVESTIGACOES_ACIDENTES', RESEED,0);


--Drop planilhaS
DROP TABLE planilha_aeronave;
DROP TABLE planilha_ocorrencias;
DROP TABLE planilha_municipios;
DROP TABLE planilha_ocorrencia_tipo;
DROP TABLE planilha_fator_contribuinte;