CREATE VIEW Vw_TOTAL_OCORRENCIAS AS
	SELECT COUNT(*) AS TOTAL_ACIDADENTES FROM OCORRENCIAS_AERONAVES;



CREATE VIEW Vw_TOTAL_TIPO_FALHA AS 
	SELECT TPF_TIPO, COUNT(*) AS TOTAL FROM TIPOS_FALHAS
	JOIN INVESTIGACOES_ACIDENTES ON IVA_TPF_ID = TPF_ID
	JOIN OCORRENCIAS_AERONAVES ON IVA_OAC_ID = OAC_ID
	GROUP BY TPF_TIPO;


CREATE VIEW Vw_Total_Ocorrencias_Ano AS
	SELECT YEAR(OAC_DIA) AS Ano, COUNT(*) AS Total_Ocorrencias
	FROM OCORRENCIAS_AERONAVES
	GROUP BY YEAR(OAC_DIA);


CREATE VIEW Vw_Total_Acidentes_Modelo AS
SELECT 
    MDA_MODELO AS MODELO, 
    COUNT(*) AS TOTAL_ACIDENTES
FROM MODELOS_AERONAVES
JOIN AERONAVES ON ARV_MDA_ID = MDA_ID
JOIN OCORRENCIAS_AERONAVES ON OAC_ARV_ID = ARV_ID
GROUP BY MDA_MODELO
 

CREATE VIEW Vw_Total_Acidentes_Segmento AS
SELECT 
    TPS_OPERACAO AS OPERACAO, 
    COUNT(*) AS TOTAL_ACIDENTES
FROM TIPOS_SEGMENTOS
JOIN OCORRENCIAS_AERONAVES ON OAC_TPS_ID  = TPS_ID
GROUP BY TPS_OPERACAO;


CREATE VIEW VW_TOP5_FABRICANTES_OCORRENCIAS AS
WITH RANKED_FABRICANTES AS (
    SELECT 
        FBA_NOME, 
        YEAR(OAC_DIA) AS ANO, 
        COUNT(*) AS TOTAL,
        SUM(COUNT(*)) OVER (PARTITION BY FBA_NOME) AS TOTAL_GERAL
    FROM FABRICANTES_AERONAVES
    JOIN MODELOS_AERONAVES ON MDA_FBA_ID = FBA_ID
    JOIN AERONAVES ON ARV_MDA_ID = MDA_ID
    JOIN OCORRENCIAS_AERONAVES ON OAC_ARV_ID = ARV_ID
    GROUP BY FBA_NOME, YEAR(OAC_DIA)
)
SELECT * 
FROM RANKED_FABRICANTES
WHERE FBA_NOME IN (
    SELECT TOP 5 FBA_NOME
    FROM RANKED_FABRICANTES
    GROUP BY FBA_NOME
    ORDER BY SUM(TOTAL) DESC
);
